# This file controls the settings for your Quarto template from www.marvinschmitt.com

# website settings
website:
  title: "Sharaj Kunjar"                                # Your name
  description: "Sharaj's personal academic website"   # A brief slogan (optional)
  image: img/Sharaj.jpg
  
  #the thing on the left of the tab
  #favicon: img/favicon.png
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    #logo: /img/logo.png
    
    # your sub-pages
    left:
      - text: "Projects"
        href: projects/index.qmd
      - text: "CV"
        href: cv/index.qmd
    

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
      <span class="faux-block">&#169; 2024 Sharaj Kunjar CC BY-SA 4.0</span>
    center: 
      - text: "{{< iconify fa6-brands google-scholar size=large >}}"
        href: https://scholar.google.com/citations?user=8Aofwe4AAAAJ&hl=en&oi=ao
      - icon: twitter
        href: https://twitter.com/yaassakka
      - icon: linkedin
        href: https://www.linkedin.com/in/sharaj-kunjar-125ba6201/
      - icon: envelope
        aria-label: email
        href: "mailto:sharaj.kunjar@gmail.com"
      - text: "{{<iconify fa6-brands github size=large >}}"
        href: https://github.com/sharajk/
    right: |
      <span class="faux-block"><a href="https://github.com/marvinschmitt/quarto-website-template/">Template adapted from Marvin Schmitt</a></span>

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - minty
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true